#!/usr/bin/env python3
"""Plan and apply safe incremental AppSpec changes to a generated application."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from scaffold_app import (
    SpecError,
    compile_navigation,
    compile_permissions,
    compile_registry,
    compile_report,
    database_object_name,
    sql_default,
    sql_identifier,
    sql_string,
    sql_type,
    validate_spec,
)


MIGRATION_NAME_PATTERN = re.compile(r"^[a-z][a-z0-9_]{0,47}$")
MANAGED_MARKERS = ("GENERATED BY APP FACTORY", "GENERATED BY RIEL APP FACTORY")


@dataclass
class EvolutionPlan:
    old_fingerprint: str
    new_fingerprint: str
    changes: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    blocked: list[str] = field(default_factory=list)
    sql: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return self.old_fingerprint != self.new_fingerprint

    @property
    def safe_to_apply(self) -> bool:
        return self.changed and not self.blocked


def canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def fingerprint(spec: dict[str, Any]) -> str:
    return hashlib.sha256(canonical_json(spec).encode("utf-8")).hexdigest()


def keyed(items: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {item["key"]: item for item in items}


def enum_keys(field_spec: dict[str, Any]) -> list[str]:
    return [option["key"] for option in field_spec.get("options", [])]


def compile_column(field_spec: dict[str, Any]) -> str:
    parts = [sql_identifier(field_spec["key"]), sql_type(field_spec)]
    if field_spec.get("required"):
        parts.append("NOT NULL")
    default_value = sql_default(field_spec)
    if default_value is not None:
        parts.append(f"DEFAULT {default_value}")
    if field_spec.get("unique"):
        parts.append("UNIQUE")
    return " ".join(parts)


def compile_enum_constraint(entity_key: str, field_spec: dict[str, Any]) -> str:
    values = ", ".join(sql_string(option["key"]) for option in field_spec["options"])
    constraint = database_object_name("ck", entity_key, field_spec["key"])
    return (
        f"ALTER TABLE {sql_identifier(entity_key)} ADD CONSTRAINT {sql_identifier(constraint)} "
        f"CHECK ({sql_identifier(field_spec['key'])} IN ({values}));"
    )


def compile_new_entity_table(entity: dict[str, Any]) -> list[str]:
    columns = [
        "  id uuid PRIMARY KEY DEFAULT gen_random_uuid()",
        "  created_at timestamptz NOT NULL DEFAULT now()",
        "  updated_at timestamptz NOT NULL DEFAULT now()",
    ]
    constraints: list[str] = []
    for field_spec in entity["fields"]:
        columns.append(f"  {compile_column(field_spec)}")
        if field_spec["type"] == "enum":
            values = ", ".join(sql_string(option["key"]) for option in field_spec["options"])
            constraint = database_object_name("ck", entity["key"], field_spec["key"])
            constraints.append(
                f"  CONSTRAINT {sql_identifier(constraint)} "
                f"CHECK ({sql_identifier(field_spec['key'])} IN ({values}))"
            )
    for relationship in entity.get("relationships", []):
        if relationship["type"] != "belongs_to":
            continue
        column = f"  {sql_identifier(relationship['key'] + '_id')} uuid"
        if relationship.get("required"):
            column += " NOT NULL"
        columns.append(column)
    body = columns + constraints
    return [
        f"CREATE TABLE {sql_identifier(entity['key'])} (",
        ",\n".join(body),
        ");",
        f"CREATE TRIGGER {sql_identifier(database_object_name('trg', entity['key'], 'updated_at'))}",
        f"  BEFORE UPDATE ON {sql_identifier(entity['key'])}",
        "  FOR EACH ROW EXECUTE FUNCTION app_set_updated_at();",
    ]


def compile_relationship(entity_key: str, relationship: dict[str, Any], *, add_column: bool) -> list[str]:
    statements: list[str] = []
    column_name = relationship["key"] + "_id"
    if add_column:
        column = f"ALTER TABLE {sql_identifier(entity_key)} ADD COLUMN {sql_identifier(column_name)} uuid"
        if relationship.get("required"):
            column += " NOT NULL"
        statements.append(column + ";")
    on_delete = {
        "restrict": "RESTRICT",
        "cascade": "CASCADE",
        "set_null": "SET NULL",
    }[relationship.get("on_delete", "restrict")]
    constraint = database_object_name("fk", entity_key, relationship["key"])
    index_name = database_object_name("ix", entity_key, relationship["key"])
    statements.extend(
        [
            f"ALTER TABLE {sql_identifier(entity_key)} ADD CONSTRAINT {sql_identifier(constraint)} "
            f"FOREIGN KEY ({sql_identifier(column_name)}) "
            f"REFERENCES {sql_identifier(relationship['target'])}(id) ON DELETE {on_delete};",
            f"CREATE INDEX {sql_identifier(index_name)} ON {sql_identifier(entity_key)} "
            f"({sql_identifier(column_name)});",
        ]
    )
    return statements


def compile_search_index(entity_key: str, field_key: str) -> str:
    index_name = database_object_name("ix", entity_key, field_key)
    return (
        f"CREATE INDEX {sql_identifier(index_name)} ON {sql_identifier(entity_key)} "
        f"({sql_identifier(field_key)});"
    )


def plan_keyed_runtime_changes(
    plan: EvolutionPlan,
    label: str,
    old_items: list[dict[str, Any]],
    new_items: list[dict[str, Any]],
) -> None:
    old_map = keyed(old_items)
    new_map = keyed(new_items)
    for key in sorted(new_map.keys() - old_map.keys()):
        plan.changes.append(f"{label} added: {key}")
    for key in sorted(old_map.keys() - new_map.keys()):
        plan.changes.append(f"{label} removed: {key}")
    for key in sorted(old_map.keys() & new_map.keys()):
        if old_map[key] != new_map[key]:
            plan.changes.append(f"{label} updated: {key}")


def plan_field_change(
    plan: EvolutionPlan,
    entity_key: str,
    old_field: dict[str, Any],
    new_field: dict[str, Any],
) -> None:
    field_key = old_field["key"]
    path = f"{entity_key}.{field_key}"
    if old_field["type"] != new_field["type"]:
        plan.blocked.append(
            f"Field type change requires a reviewed data migration: {path} "
            f"({old_field['type']} -> {new_field['type']})"
        )
        return

    if old_field.get("required", False) != new_field.get("required", False):
        if new_field.get("required"):
            plan.blocked.append(f"Making an existing field required needs a backfill plan: {path}")
        else:
            plan.sql.append(
                f"ALTER TABLE {sql_identifier(entity_key)} ALTER COLUMN "
                f"{sql_identifier(field_key)} DROP NOT NULL;"
            )
            plan.changes.append(f"Field made optional: {path}")

    if old_field.get("unique", False) != new_field.get("unique", False):
        plan.blocked.append(f"Changing uniqueness requires duplicate analysis and explicit review: {path}")

    old_has_default = "default" in old_field
    new_has_default = "default" in new_field
    if old_has_default != new_has_default or (
        old_has_default and new_has_default and old_field.get("default") != new_field.get("default")
    ):
        if "default" in new_field:
            default_value = sql_default(new_field)
            plan.sql.append(
                f"ALTER TABLE {sql_identifier(entity_key)} ALTER COLUMN {sql_identifier(field_key)} "
                f"SET DEFAULT {default_value};"
            )
        else:
            plan.sql.append(
                f"ALTER TABLE {sql_identifier(entity_key)} ALTER COLUMN {sql_identifier(field_key)} DROP DEFAULT;"
            )
        plan.changes.append(f"Field default updated: {path}")

    if old_field["type"] == "enum":
        old_options = enum_keys(old_field)
        new_options = enum_keys(new_field)
        removed = sorted(set(old_options) - set(new_options))
        if removed:
            plan.blocked.append(
                f"Removing enum values requires a data migration for {path}: {', '.join(removed)}"
            )
        elif old_options != new_options:
            constraint = database_object_name("ck", entity_key, field_key)
            plan.sql.extend(
                [
                    f"ALTER TABLE {sql_identifier(entity_key)} DROP CONSTRAINT {sql_identifier(constraint)};",
                    compile_enum_constraint(entity_key, new_field),
                ]
            )
            plan.changes.append(f"Enum options expanded or reordered: {path}")
        elif old_field.get("options") != new_field.get("options"):
            plan.changes.append(f"Enum option labels updated: {path}")

    old_searchable = old_field.get("searchable", False)
    new_searchable = new_field.get("searchable", False)
    if old_searchable != new_searchable:
        if new_searchable:
            plan.sql.append(compile_search_index(entity_key, field_key))
            plan.changes.append(f"Search index added: {path}")
        else:
            plan.warnings.append(f"Search index retained although the field is no longer searchable: {path}")
            plan.changes.append(f"Field removed from runtime search: {path}")

    runtime_keys = {"label", "help"}
    if any(old_field.get(key) != new_field.get(key) for key in runtime_keys):
        plan.changes.append(f"Field presentation updated: {path}")


def plan_relationship_change(
    plan: EvolutionPlan,
    entity_key: str,
    old_relationship: dict[str, Any],
    new_relationship: dict[str, Any],
) -> None:
    relationship_key = old_relationship["key"]
    path = f"{entity_key}.{relationship_key}"
    if old_relationship["type"] != new_relationship["type"]:
        plan.blocked.append(f"Relationship type change requires schema review: {path}")
        return
    if old_relationship["type"] != "belongs_to":
        plan.changes.append(f"Inverse relationship metadata updated: {path}")
        return
    for key in ("type", "target", "on_delete"):
        if old_relationship.get(key, "restrict" if key == "on_delete" else None) != new_relationship.get(
            key, "restrict" if key == "on_delete" else None
        ):
            plan.blocked.append(f"Relationship {key} change requires constraint review: {path}")
            return
    if old_relationship.get("required", False) != new_relationship.get("required", False):
        column_name = relationship_key + "_id"
        if new_relationship.get("required"):
            plan.blocked.append(f"Making an existing relationship required needs a backfill plan: {path}")
        else:
            plan.sql.append(
                f"ALTER TABLE {sql_identifier(entity_key)} ALTER COLUMN "
                f"{sql_identifier(column_name)} DROP NOT NULL;"
            )
            plan.changes.append(f"Relationship made optional: {path}")
    if old_relationship.get("label") != new_relationship.get("label"):
        plan.changes.append(f"Relationship presentation updated: {path}")


def plan_existing_entity(
    plan: EvolutionPlan,
    old_entity: dict[str, Any],
    new_entity: dict[str, Any],
) -> None:
    entity_key = old_entity["key"]
    old_fields = keyed(old_entity["fields"])
    new_fields = keyed(new_entity["fields"])
    for field_key in sorted(old_fields.keys() - new_fields.keys()):
        plan.blocked.append(f"Removing or renaming a field requires a reviewed data migration: {entity_key}.{field_key}")
    for field_key in sorted(new_fields.keys() - old_fields.keys()):
        field_spec = new_fields[field_key]
        path = f"{entity_key}.{field_key}"
        if field_spec.get("required") and (
            "default" not in field_spec or field_spec.get("default") is None
        ):
            plan.blocked.append(f"A required field on an existing entity needs a default or backfill plan: {path}")
            continue
        if field_spec.get("unique") and "default" in field_spec:
            plan.blocked.append(f"A unique field with one default may conflict with existing rows: {path}")
            continue
        plan.sql.append(
            f"ALTER TABLE {sql_identifier(entity_key)} ADD COLUMN {compile_column(field_spec)};"
        )
        if field_spec["type"] == "enum":
            plan.sql.append(compile_enum_constraint(entity_key, field_spec))
        if field_spec.get("searchable"):
            plan.sql.append(compile_search_index(entity_key, field_key))
        plan.changes.append(f"Field added: {path}")
    for field_key in sorted(old_fields.keys() & new_fields.keys()):
        if old_fields[field_key] != new_fields[field_key]:
            plan_field_change(plan, entity_key, old_fields[field_key], new_fields[field_key])

    old_relationships = keyed(old_entity.get("relationships", []))
    new_relationships = keyed(new_entity.get("relationships", []))
    for relationship_key in sorted(old_relationships.keys() - new_relationships.keys()):
        if old_relationships[relationship_key]["type"] == "belongs_to":
            plan.blocked.append(
                f"Removing or renaming a relationship requires a reviewed data migration: "
                f"{entity_key}.{relationship_key}"
            )
        else:
            plan.changes.append(f"Inverse relationship metadata removed: {entity_key}.{relationship_key}")
    for relationship_key in sorted(new_relationships.keys() - old_relationships.keys()):
        relationship = new_relationships[relationship_key]
        path = f"{entity_key}.{relationship_key}"
        if relationship["type"] != "belongs_to":
            plan.changes.append(f"Inverse relationship metadata added: {path}")
            continue
        if relationship.get("required"):
            plan.blocked.append(f"A required relationship on an existing entity needs a backfill plan: {path}")
            continue
        plan.sql.extend(compile_relationship(entity_key, relationship, add_column=True))
        plan.changes.append(f"Relationship added: {path}")
    for relationship_key in sorted(old_relationships.keys() & new_relationships.keys()):
        if old_relationships[relationship_key] != new_relationships[relationship_key]:
            plan_relationship_change(
                plan,
                entity_key,
                old_relationships[relationship_key],
                new_relationships[relationship_key],
            )

    presentation_keys = {"label", "label_plural", "description", "title_field", "attachments", "permissions"}
    if any(old_entity.get(key) != new_entity.get(key) for key in presentation_keys):
        plan.changes.append(f"Entity metadata or permissions updated: {entity_key}")


def plan_evolution(old_spec: dict[str, Any], new_spec: dict[str, Any]) -> EvolutionPlan:
    plan = EvolutionPlan(fingerprint(old_spec), fingerprint(new_spec))
    if not plan.changed:
        return plan
    if old_spec["version"] != new_spec["version"]:
        plan.blocked.append(
            f"AppSpec version changes require a compiler upgrade: {old_spec['version']} -> {new_spec['version']}"
        )
    if old_spec["app"]["key"] != new_spec["app"]["key"]:
        plan.blocked.append("Changing the application key is not an incremental operation.")
    if old_spec["app"] != new_spec["app"]:
        plan.changes.append("Application metadata updated")
        if old_spec["app"].get("theme") != new_spec["app"].get("theme"):
            plan.warnings.append(
                "Theme metadata changed; review custom CSS because evolution does not overwrite runtime-owned styles."
            )

    old_roles = keyed(old_spec["roles"])
    new_roles = keyed(new_spec["roles"])
    for role_key in sorted(old_roles.keys() - new_roles.keys()):
        plan.blocked.append(f"Removing a role requires reassignment of existing users: {role_key}")
    for role_key in sorted(new_roles.keys() - old_roles.keys()):
        role = new_roles[role_key]
        plan.sql.append(
            "INSERT INTO app_role (key, label) VALUES "
            f"({sql_string(role_key)}, {sql_string(role['label'])}) "
            "ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label;"
        )
        plan.changes.append(f"Role added: {role_key}")
    for role_key in sorted(old_roles.keys() & new_roles.keys()):
        if old_roles[role_key]["label"] != new_roles[role_key]["label"]:
            role = new_roles[role_key]
            plan.sql.append(
                "INSERT INTO app_role (key, label) VALUES "
                f"({sql_string(role_key)}, {sql_string(role['label'])}) "
                "ON CONFLICT (key) DO UPDATE SET label = EXCLUDED.label;"
            )
            plan.changes.append(f"Role label updated: {role_key}")
        if old_roles[role_key].get("capabilities", []) != new_roles[role_key].get("capabilities", []):
            plan.changes.append(f"Role capabilities updated: {role_key}")

    old_entities = keyed(old_spec["entities"])
    new_entities = keyed(new_spec["entities"])
    for entity_key in sorted(old_entities.keys() - new_entities.keys()):
        plan.blocked.append(f"Removing or renaming an entity requires a reviewed data migration: {entity_key}")

    new_entity_keys = sorted(new_entities.keys() - old_entities.keys())
    for entity_key in new_entity_keys:
        plan.sql.extend(compile_new_entity_table(new_entities[entity_key]))
        plan.changes.append(f"Entity added: {entity_key}")

    for entity_key in sorted(old_entities.keys() & new_entities.keys()):
        if old_entities[entity_key] != new_entities[entity_key]:
            plan_existing_entity(plan, old_entities[entity_key], new_entities[entity_key])

    for entity_key in new_entity_keys:
        entity = new_entities[entity_key]
        for relationship in entity.get("relationships", []):
            if relationship["type"] == "belongs_to":
                plan.sql.extend(compile_relationship(entity_key, relationship, add_column=False))
        for field_spec in entity["fields"]:
            if field_spec.get("searchable"):
                plan.sql.append(compile_search_index(entity_key, field_spec["key"]))

    plan_keyed_runtime_changes(plan, "View", old_spec["views"], new_spec["views"])
    plan_keyed_runtime_changes(plan, "Rule", old_spec.get("rules", []), new_spec.get("rules", []))
    if old_spec.get("decisions", []) != new_spec.get("decisions", []):
        plan.changes.append("Decisions updated")
    return plan


def next_migration_path(project: Path, migration_name: str) -> Path:
    if not MIGRATION_NAME_PATTERN.fullmatch(migration_name):
        raise SpecError("Migration name must be snake_case and at most 48 characters.")
    migration_directory = project / "database" / "generated"
    existing_numbers: list[int] = []
    for path in migration_directory.glob("*.sql"):
        match = re.match(r"^(\d{3})_", path.name)
        if match:
            existing_numbers.append(int(match.group(1)))
    if not existing_numbers:
        raise SpecError("No generated migration baseline found.")
    number = max(existing_numbers) + 1
    if number > 999:
        raise SpecError("Generated migration sequence is exhausted.")
    return migration_directory / f"{number:03d}_{migration_name}.sql"


def compile_migration(plan: EvolutionPlan) -> str:
    lines = [
        "-- GENERATED BY APP FACTORY EVOLUTION. DO NOT EDIT AFTER DEPLOYMENT.",
        f"-- Previous AppSpec: {plan.old_fingerprint}",
        f"-- New AppSpec: {plan.new_fingerprint}",
        "BEGIN;",
        *plan.sql,
        "COMMIT;",
        "",
    ]
    return "\n".join(lines)


def render_report(plan: EvolutionPlan, migration: Path | None, applied: bool) -> str:
    lines = [
        "# AppSpec evolution report",
        "",
        f"- Previous fingerprint: `{plan.old_fingerprint}`",
        f"- New fingerprint: `{plan.new_fingerprint}`",
        f"- Mode: {'applied' if applied else 'plan only'}",
        f"- Migration: `{migration.as_posix()}`" if migration else "- Migration: none (runtime metadata only)",
        "",
        "## Changes",
        "",
        *([f"- {item}" for item in plan.changes] or ["- No semantic changes."]),
        "",
        "## Warnings",
        "",
        *([f"- {item}" for item in plan.warnings] or ["- None."]),
        "",
        "## Blocked changes",
        "",
        *([f"- {item}" for item in plan.blocked] or ["- None."]),
        "",
        "## Required verification",
        "",
        "- Review the migration and generated diff before applying it to any database.",
        "- Commit or otherwise snapshot source and database recovery state.",
        "- Run `pnpm db:apply`, `pnpm db:smoke`, and `pnpm typecheck` or `pnpm build`.",
        "- Verify affected permissions, rules, views, and one complete browser flow.",
        "- Deploy through preview before production when the environment supports it.",
        "",
    ]
    return "\n".join(lines)


def verify_project(project: Path) -> dict[str, Any]:
    required = [
        project / "app-spec.json",
        project / "database" / "generated" / "001_initial.sql",
        project / "src" / "generated" / "app-spec.ts",
        project / "src" / "generated" / "navigation.ts",
        project / "src" / "generated" / "permissions.ts",
    ]
    missing = [str(path.relative_to(project)) for path in required if not path.is_file()]
    if missing:
        raise SpecError(f"Project is not a complete generated application; missing: {', '.join(missing)}")
    for path in required[1:]:
        if not any(marker in path.read_text(encoding="utf-8") for marker in MANAGED_MARKERS):
            raise SpecError(f"Managed-file marker missing: {path.relative_to(project)}")
    try:
        spec = json.loads(required[0].read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise SpecError(f"Current app-spec.json is invalid JSON: {error}") from error
    errors = validate_spec(spec)
    if errors:
        raise SpecError("Current AppSpec is invalid:\n- " + "\n- ".join(errors))
    return spec


def atomic_write_files(files: dict[Path, str]) -> None:
    temporary_paths: list[tuple[Path, Path]] = []
    try:
        for destination, content in files.items():
            destination.parent.mkdir(parents=True, exist_ok=True)
            with tempfile.NamedTemporaryFile(
                mode="w",
                encoding="utf-8",
                newline="\n",
                dir=destination.parent,
                prefix=f".{destination.name}.",
                suffix=".riel-tmp",
                delete=False,
            ) as handle:
                handle.write(content)
                temporary_paths.append((Path(handle.name), destination))
        for temporary, destination in temporary_paths:
            temporary.replace(destination)
    finally:
        for temporary, _ in temporary_paths:
            temporary.unlink(missing_ok=True)


def apply_evolution(
    project: Path,
    new_spec: dict[str, Any],
    plan: EvolutionPlan,
    migration_name: str,
) -> Path | None:
    if not plan.safe_to_apply:
        raise SpecError("Evolution is not safe to apply; review blocked changes first.")
    migration = next_migration_path(project, migration_name) if plan.sql else None
    files = {
        project / "app-spec.json": json.dumps(new_spec, ensure_ascii=False, indent=2) + "\n",
        project / "src" / "generated" / "app-spec.ts": compile_registry(new_spec),
        project / "src" / "generated" / "navigation.ts": compile_navigation(new_spec),
        project / "src" / "generated" / "permissions.ts": compile_permissions(new_spec),
        project / "BUILD_REPORT.md": compile_report(new_spec),
    }
    if migration:
        files[migration] = compile_migration(plan)
    files[project / "EVOLUTION_REPORT.md"] = render_report(
        plan,
        migration.relative_to(project) if migration else None,
        applied=True,
    )
    atomic_write_files(files)
    return migration


def load_proposed_spec(path: Path) -> dict[str, Any]:
    try:
        spec = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as error:
        raise SpecError(f"Proposed spec not found: {path}") from error
    except json.JSONDecodeError as error:
        raise SpecError(
            f"Proposed spec has invalid JSON at line {error.lineno}, column {error.colno}: {error.msg}"
        ) from error
    errors = validate_spec(spec)
    if errors:
        raise SpecError("Proposed AppSpec is invalid:\n- " + "\n- ".join(errors))
    return spec


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", required=True, type=Path, help="Existing generated application")
    parser.add_argument("--spec", required=True, type=Path, help="Proposed AppSpec outside the project")
    parser.add_argument("--apply", action="store_true", help="Write managed files and a new migration")
    parser.add_argument(
        "--migration-name",
        default="appspec_evolution",
        help="Snake-case suffix for a generated migration",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    project = args.project.resolve()
    proposed_path = args.spec.resolve()
    if proposed_path == project / "app-spec.json":
        print("Use a separate proposed AppSpec so the current version remains available for comparison.")
        return 2
    try:
        old_spec = verify_project(project)
        new_spec = load_proposed_spec(proposed_path)
        plan = plan_evolution(old_spec, new_spec)
        migration = next_migration_path(project, args.migration_name).relative_to(project) if plan.sql else None
    except SpecError as error:
        print(str(error))
        return 2

    print(render_report(plan, migration, applied=False))
    if not plan.changed:
        print("No changes detected.")
        return 0
    if plan.blocked:
        print("Evolution blocked. No files were changed.")
        return 3
    if not args.apply:
        print("Plan is safe. Re-run with --apply after reviewing it.")
        return 0
    try:
        written_migration = apply_evolution(
            project,
            new_spec,
            plan,
            args.migration_name,
        )
    except SpecError as error:
        print(str(error))
        return 2
    print(f"Evolution applied: {project}")
    print(f"Migration: {written_migration.relative_to(project) if written_migration else 'none'}")
    print("Client extensions were not modified.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
